### ISSUE TITLE
Hero Gates - Graphics - No Gate Number

### ISSUE THREAD

**Issue by Luke44** [rainlizard/Unearth#57]
Here is v0.24c showing a Hero Gate with correct graphics, but more importantly, the Gate #.
<img width="1928" height="1040" alt="Image" src="https://github.com/user-attachments/assets/1637e2a0-6ec8-4be0-8c68-3fa89bbf697e" />

Here is v0.59.789 showing Hero Gates with botched graphics, but more importantly, Gate # is unavailable, which is very bugged.
Graphics - It's more filled out, and the inner blue portal part is non existent with a UI white outline.
Gate # - This is important for scripting.
<img width="1928" height="1040" alt="Image" src="https://github.com/user-attachments/assets/e7422b37-e956-40b3-9931-cf54eb6b744a" />

It seems things were removed, instead of just adding improvements.
This makes this version unusable if I want to use Hero Gates like normal.

**Comment by rainlizard** [comment]
The herogates missing their number is a familiar bug, but it was fixed a while ago in 0.52.662:
```
0.52.662 - 10/2/2025
- Fixed Herogates breaking when pressing 'Undo'
```
However any maps made during a certain time period may have been inflicted with gates missing their numbers. To fix them, you need to delete the hero gate and place it again, then save the map. (tell me if this works for you)

In v0.59.789 I can't recreate your issues. The numbers appear for me, the hero gates don't have that white inner line for me, the fairies being blurry like that is strange too, they have crisp pixels on my PC:
<img width="2556" height="1388" alt="Image" src="https://github.com/user-attachments/assets/80e38428-1248-443a-8764-13bf7c1a72c2" />

There's a lot of strangeness going on here, but I don't think I can solve anything without more information.

**Comment by Luke44** [comment]
My image shows me whole window. v0.59 is what I have, and there's no Hero Gate #, but v0.24c still works.
This has nothing to do with Undo. — I saved my map, and opened it, and the numbers and the window items are still missing.
Look at my right side UI for the Gate. There's no Gate # like in v0.24c, and there's no new item called Orientation.

**Comment by rainlizard** [comment]
Unfortunately I can't reproduce your bug no matter what I do (which is necessary in order for me to fix it). I've tried all sorts of circumstances but the gate number always appears for me.

What are your full system specs? Your exact OS (Windows 10, Windows 11?), your CPU, GPU, RAM, etc.

You could also zip up the problematic map and upload it here (drag the zip file into the github message box) so I can analyze it.

Are you absolutely sure this isn't specific to ONE map? Are you able to create another map that is also missing hero gate numbers?

**Comment by Luke44** [comment]
My scenarios, as I test everything, is I create a new map (CLASSIC DK 85x85), and make some room and place the Gate. That's all I've done. What you saw with the Fairies was the absolutely beginning my that new map.

OS Win11— Not that it makes a diff:
Processor	12th Gen Intel(R) Core(TM) i7-1255U   1.70 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor

Perhaps things are working for KFX but are breaking for Classic?

**Comment by Loobinex** [comment]
> My scenarios, as I test everything, is I create a new map (CLASSIC DK 85x85), and make some room and place the Gate. That's all I've done. What you saw with the Fairies was the absolutely beginning my that new map.
> 
> OS Win11— Not that it makes a diff: Processor 12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz Installed RAM 16.0 GB (15.7 GB usable) System type 64-bit operating system, x64-based processor
> 
> Perhaps things are working for KFX but are breaking for Classic?

If you start a new map for KFX, does it then look correct for you?

**Comment by Luke44** [comment]
I'm interesting in being able to plat the real game with Classic maps.

**Comment by Luke44** [comment]
> Unfortunately I can't reproduce your bug no matter what I do (which is necessary in order for me to fix it). I've tried all sorts of circumstances but the gate number always appears for me. Other users on the keeperfx discord are all using the editor without these problems.
> 
> What are your full system specs? Your exact OS (Windows 10, Windows 11?), your CPU, GPU, RAM, etc.
> 
> You could also zip up the problematic map and upload it here (drag the zip file into the github message box) so I can analyze it.
> 
> Are you absolutely sure this isn't specific to ONE map? Are you able to create another map that is also missing hero gate numbers?

Referring to latest:
The priority should be the Inspector fields being missing.
So yeah, create a real map and maybe you'll replicate it.

**Comment by Loobinex** [comment]
I tried it on a classic format, and it's still looking good for me. 

In map settings, you can switch an existing map between formats, if you do so, does it switch between looking good and bad for you?

**Comment by rainlizard** [comment]
I recreated the issue!

I had to set the game executable to `keeper.exe`, then restart unearth, then start a new map with Classic selected. The reason I had trouble is because the issue doesn't appear if `keeperfx.exe` is initially selected and then you try to switch to the original `keeper.exe` (had to restart the application after switching).

I'll have a fix soon.

**Comment by Luke44** [comment]
BTW, are you still using Godot 2?
A while ago, I sought out to make a text edit using Godot 3, and it had nothing on it like the line number etc that yours does.
So I tried Godot 2, and it's got it! -- What a downgrade they did!!!

**Comment by rainlizard** [comment]
OK try this: https://github.com/rainlizard/Unearth/releases/tag/0.60.804

The numbers should be fixed and I've changed the Hero Gate shader again, tell me if you've still got that ugly middle line.

> BTW, are you still using Godot 2?

Unearth uses Godot version 3.5.3 (the newest Godot is 4.4.1, which would require a lot of work to update to), it's never used 2.0.

> A while ago, I sought out to make a text edit using Godot 3, and it had nothing on it like the line number etc that yours does.
> So I tried Godot 2, and it's got it! -- What a downgrade they did!!!



The Godot node for the script editor is called TextEdit, you have to enable `show_line_numbers` in the inspector (or set it via GDScript). https://docs.godotengine.org/en/stable/classes/class_textedit.html

**Comment by Luke44** [comment]
I just read the notes. I wondered sup...

- I uppercased mine after download. >.< XD
